import { Seo } from "../../components/Seo";
import { Card } from "../../components/ui/Card";

export function TermsOfServicePage() {
  return (
    <>
      <Seo
        title="Terms of Service"
        description="Terms of Service for AI News Digest. Read the terms governing your use of our platform."
      />
      <div className="container-page py-8">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
          <p className="mt-2 text-sm text-slate-500">Last updated: August 2026</p>

          <div className="mt-8 space-y-8">
            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">1. Acceptance of Terms</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  By accessing or using AI News Digest (&quot;the service&quot;),
                  you agree to be bound by these Terms of Service. If you do not
                  agree to these terms, please do not use the service.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">2. Description of Service</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  AI News Digest is an AI-powered news aggregation platform that
                  collects articles from RSS sources, generates summaries using
                  artificial intelligence, and produces daily news digests for
                  registered users.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">3. User Accounts</h2>
                <ul className="mt-3 list-disc space-y-2 pl-5 text-slate-700">
                  <li>
                    You must provide accurate and complete information when
                    creating an account.
                  </li>
                  <li>
                    You are responsible for maintaining the security of your
                    account credentials.
                  </li>
                  <li>
                    You must notify us immediately of any unauthorized use of
                    your account.
                  </li>
                  <li>
                    We reserve the right to suspend or terminate accounts that
                    violate these terms.
                  </li>
                </ul>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">4. Acceptable Use</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  You agree not to:
                </p>
                <ul className="mt-3 list-disc space-y-2 pl-5 text-slate-700">
                  <li>Use the service for any unlawful purpose</li>
                  <li>Attempt to gain unauthorized access to our systems</li>
                  <li>Interfere with or disrupt the service or servers</li>
                  <li>Scrape or systematically extract data without permission</li>
                  <li>Impersonate another person or entity</li>
                  <li>Transmit malicious code or harmful content</li>
                </ul>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">5. Content and Intellectual Property</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  The original articles aggregated by our service remain the
                  intellectual property of their respective publishers. Our AI
                  summaries and digest compilations are generated for personal,
                  non-commercial use. You may not redistribute or commercially
                  exploit content without permission from the original sources.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">6. AI-Generated Content</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  Summaries and digests are generated by artificial intelligence
                  and may contain inaccuracies. We do not guarantee the accuracy,
                  completeness, or reliability of AI-generated content. Users
                  should verify important information against original sources.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">7. Email Communications</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  By registering, you consent to receive service-related emails
                  including daily digests and account notifications. You may
                  unsubscribe from marketing communications at any time through
                  your account settings.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">8. Limitation of Liability</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  The service is provided &quot;as is&quot; without warranties of
                  any kind. We shall not be liable for any indirect, incidental,
                  special, or consequential damages arising from your use of the
                  service. Our total liability shall not exceed the amount paid
                  by you in the twelve months preceding the claim.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">9. Indemnification</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  You agree to indemnify and hold harmless AI News Digest and its
                  operators from any claims, damages, or expenses arising from
                  your use of the service or violation of these terms.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">10. Modifications to Terms</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  We reserve the right to modify these terms at any time. Material
                  changes will be communicated via email or a prominent notice on
                  our website. Continued use after changes constitutes acceptance
                  of the modified terms.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">11. Governing Law</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  These terms shall be governed by and construed in accordance
                  with the laws applicable in the jurisdiction of operation,
                  without regard to conflict of law provisions.
                </p>
              </section>
            </Card>

            <Card>
              <section>
                <h2 className="text-xl font-semibold text-slate-900">12. Contact</h2>
                <p className="mt-3 text-slate-700 leading-relaxed">
                  For questions about these Terms of Service, please contact us
                  at the email address provided on our website.
                </p>
              </section>
            </Card>
          </div>

          <p className="mt-8 text-sm text-slate-500">
            These terms are provided as a template and should be reviewed by a
            qualified legal professional before publication.
          </p>
        </div>
      </div>
    </>
  );
}
